import 'dart:math';
import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';
import 'package:get/get.dart';
import 'package:graphql_flutter/graphql_flutter.dart';
import '../../domain/usecase/create_store_usecase.dart';
import '../../domain/usecase/bulk_upsert_products_usecase.dart';
import '../../domain/usecase/get_upload_logs_usecase.dart';
import '../../data/model/user_model.dart';
import '../../service_core/auth/session_manager.dart';
import '../../service_core/networks/graphql_client_provider.dart';
import '../../theme/app_theme.dart';
import '../dashboard/dashboard_binding.dart';
import '../dashboard/dashboard_page.dart';
import '../products/bulk_upload_page.dart';
import '../stores/map_picker_page.dart';

class OnboardingPage extends StatefulWidget {
  const OnboardingPage({super.key});

  @override
  State<OnboardingPage> createState() => _OnboardingPageState();
}

class _OnboardingPageState extends State<OnboardingPage> {
  late final CreateStoreUseCase _createStoreUseCase = Get.find();
  late final BulkUpsertProductsUseCase _bulkUpsertProductsUseCase = Get.find();
  late final GetUploadLogsUseCase _getUploadLogsUseCase = Get.find();

  static const _upgradeToAdminMutation = r'''
    mutation UpgradeToAdmin($storeId: ID!) {
      upgradeToAdmin(storeId: $storeId) {
        id name email role roles storeId
      }
    }
  ''';

  int _step = 0; // 0 = store details, 1 = inventory, 2 = done
  bool _isSaving = false;
  String? _createdStoreId;
  String? _createdStoreName;

  // Form fields
  final _nameCtrl = TextEditingController();
  final _cityCtrl = TextEditingController();
  final _addressCtrl = TextEditingController();
  final _storeCodeCtrl = TextEditingController();
  double? _lat;
  double? _lon;
  bool _locating = false;

  @override
  void initState() {
    super.initState();
    _nameCtrl.addListener(_onNameOrCityChanged);
    _cityCtrl.addListener(_onNameOrCityChanged);
  }

  @override
  void dispose() {
    _nameCtrl.dispose();
    _cityCtrl.dispose();
    _addressCtrl.dispose();
    _storeCodeCtrl.dispose();
    super.dispose();
  }

  void _onNameOrCityChanged() {
    final code = _storeCodeCtrl.text;
    // Only auto-update if user hasn't manually set a custom code
    if (code.isEmpty || _isAutoGenerated(code)) {
      _storeCodeCtrl.text = _generateCode();
    }
  }

  bool _isAutoGenerated(String code) => RegExp(r'^[A-Z]{3}-[A-Z]{3}-\d{4}$').hasMatch(code);

  String _generateCode() {
    final rng = Random();
    final nameLetters = _nameCtrl.text.replaceAll(RegExp(r'[^a-zA-Z]'), '');
    final cityLetters = _cityCtrl.text.replaceAll(RegExp(r'[^a-zA-Z]'), '');
    final namePrefix = nameLetters.substring(0, nameLetters.length.clamp(0, 3)).toUpperCase().padRight(3, 'X');
    final cityPrefix = cityLetters.substring(0, cityLetters.length.clamp(0, 3)).toUpperCase().padRight(3, 'X');
    final digits = (1000 + rng.nextInt(9000)).toString();
    return '$namePrefix-$cityPrefix-$digits';
  }

  Future<void> _pickOnMap() async {
    final result = await Navigator.push<MapPickerResult>(
      context,
      MaterialPageRoute(
        builder: (_) => MapPickerPage(
          initialLat: _lat ?? 20.5937,
          initialLon: _lon ?? 78.9629,
        ),
      ),
    );
    if (result != null) {
      setState(() {
        _lat = result.latitude;
        _lon = result.longitude;
      });
      // Auto-fill address if empty
      if (_addressCtrl.text.trim().isEmpty &&
          result.address != 'Tap on the map to place the pin' &&
          result.address != 'Could not fetch address') {
        _addressCtrl.text = result.address;
      }
    }
  }

  Future<void> _useCurrentLocation() async {
    setState(() => _locating = true);
    try {
      bool serviceEnabled = await Geolocator.isLocationServiceEnabled();
      if (!serviceEnabled) {
        Get.snackbar('Location Off', 'Please enable location services.',
            backgroundColor: Colors.orange.withValues(alpha: 0.85), colorText: Colors.white);
        return;
      }
      LocationPermission permission = await Geolocator.checkPermission();
      if (permission == LocationPermission.denied) {
        permission = await Geolocator.requestPermission();
        if (permission == LocationPermission.denied) {
          Get.snackbar('Permission Denied', 'Location permission is required.',
              backgroundColor: Colors.red.withValues(alpha: 0.85), colorText: Colors.white);
          return;
        }
      }
      if (permission == LocationPermission.deniedForever) {
        Get.snackbar('Permission Denied', 'Enable location in app settings.',
            backgroundColor: Colors.red.withValues(alpha: 0.85), colorText: Colors.white);
        return;
      }
      Position? pos = await Geolocator.getLastKnownPosition();
      pos ??= await Geolocator.getCurrentPosition(
          locationSettings: const LocationSettings(accuracy: LocationAccuracy.medium, timeLimit: Duration(seconds: 10)));
      setState(() {
        _lat = pos!.latitude;
        _lon = pos.longitude;
      });
      Get.snackbar('Location Captured', 'Tap "Pick on Map" to verify the pin is on your store.',
          backgroundColor: Colors.green.withValues(alpha: 0.85), colorText: Colors.white);
    } catch (_) {
      Get.snackbar('Error', 'Could not get location.',
          backgroundColor: Colors.red.withValues(alpha: 0.85), colorText: Colors.white);
    } finally {
      setState(() => _locating = false);
    }
  }

  Future<void> _createStore() async {
    final name = _nameCtrl.text.trim();
    final city = _cityCtrl.text.trim();
    final address = _addressCtrl.text.trim();
    final code = _storeCodeCtrl.text.trim();

    if (name.isEmpty) { _showError('Store name is required'); return; }
    if (city.isEmpty) { _showError('City is required'); return; }
    if (address.isEmpty) { _showError('Address is required'); return; }
    if (_lat == null || _lon == null) { _showError('Please pick your store location on the map'); return; }

    setState(() => _isSaving = true);
    try {
      final store = await _createStoreUseCase.execute(
        name: name,
        address: '$address, $city',
        lat: _lat!,
        lon: _lon!,
        storeCode: code.isNotEmpty ? code : null,
      );

      // Upgrade user to admin and link storeId via roles-aware mutation
      final result = await GraphQLClientProvider.client.mutate(
        MutationOptions(
          document: gql(_upgradeToAdminMutation),
          variables: {'storeId': store.id},
        ),
      );
      if (result.hasException) throw Exception(result.exception.toString());
      final data = result.data?['upgradeToAdmin'] as Map<String, dynamic>?;
      if (data != null) {
        Get.find<SessionManager>().setUser(UserModel.fromJson(data));
      }

      setState(() {
        _createdStoreId = store.id;
        _createdStoreName = store.name;
        _step = 1;
      });
    } catch (e) {
      _showError(e.toString());
    } finally {
      setState(() => _isSaving = false);
    }
  }

  void _showError(String msg) {
    Get.snackbar('Error', msg,
        backgroundColor: Colors.red.withValues(alpha: 0.85), colorText: Colors.white);
  }

  void _goToDashboard() {
    Get.offAll(() => const DashboardPage(), binding: DashboardBinding());
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFF0D0620),
      body: SafeArea(
        child: AnimatedSwitcher(
          duration: const Duration(milliseconds: 300),
          child: _step == 0
              ? _StepStoreDetails(
                  key: const ValueKey(0),
                  nameCtrl: _nameCtrl,
                  cityCtrl: _cityCtrl,
                  addressCtrl: _addressCtrl,
                  storeCodeCtrl: _storeCodeCtrl,
                  lat: _lat,
                  lon: _lon,
                  locating: _locating,
                  isSaving: _isSaving,
                  onPickMap: _pickOnMap,
                  onCurrentLocation: _useCurrentLocation,
                  onNext: _createStore,
                )
              : _step == 1
                  ? _StepInventory(
                      key: const ValueKey(1),
                      storeId: _createdStoreId!,
                      storeName: _createdStoreName!,
                      bulkUpsertUseCase: _bulkUpsertProductsUseCase,
                      getLogsUseCase: _getUploadLogsUseCase,
                      onSkip: () => setState(() => _step = 2),
                      onDone: () => setState(() => _step = 2),
                    )
                  : _StepDone(
                      key: const ValueKey(2),
                      storeName: _createdStoreName!,
                      storeCode: _storeCodeCtrl.text.trim(),
                      onGoToDashboard: _goToDashboard,
                    ),
        ),
      ),
    );
  }
}

// ── Step 1: Store Details ────────────────────────────────────────────────────

class _StepStoreDetails extends StatelessWidget {
  final TextEditingController nameCtrl;
  final TextEditingController cityCtrl;
  final TextEditingController addressCtrl;
  final TextEditingController storeCodeCtrl;
  final double? lat;
  final double? lon;
  final bool locating;
  final bool isSaving;
  final VoidCallback onPickMap;
  final VoidCallback onCurrentLocation;
  final VoidCallback onNext;

  const _StepStoreDetails({
    super.key,
    required this.nameCtrl,
    required this.cityCtrl,
    required this.addressCtrl,
    required this.storeCodeCtrl,
    required this.lat,
    required this.lon,
    required this.locating,
    required this.isSaving,
    required this.onPickMap,
    required this.onCurrentLocation,
    required this.onNext,
  });

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      padding: const EdgeInsets.fromLTRB(24, 32, 24, 32),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Header
          Container(
            width: 56, height: 56,
            decoration: BoxDecoration(
              color: AppTheme.primary.withValues(alpha: 0.15),
              borderRadius: BorderRadius.circular(16),
            ),
            child: const Icon(Icons.store_mall_directory_rounded, color: AppTheme.primary, size: 28),
          ),
          const SizedBox(height: 16),
          const Text('Set Up Your Store', style: TextStyle(color: Colors.white, fontSize: 24, fontWeight: FontWeight.bold)),
          const SizedBox(height: 6),
          const Text('Enter your store details to get started on DQ.', style: TextStyle(color: Color(0xFFCDB4DB), fontSize: 14)),
          const SizedBox(height: 8),

          // Step indicator
          _StepIndicator(current: 0),
          const SizedBox(height: 28),

          _field(nameCtrl, 'Store Name', icon: Icons.storefront_rounded),
          const SizedBox(height: 12),
          _field(cityCtrl, 'City', icon: Icons.location_city_rounded),
          const SizedBox(height: 12),
          _field(addressCtrl, 'Full Address', icon: Icons.location_on_outlined, maxLines: 2),
          const SizedBox(height: 12),

          // Store code (auto-generated, editable)
          _field(
            storeCodeCtrl,
            'Store Code (auto-generated)',
            icon: Icons.tag_rounded,
            hint: 'e.g. STY-MUM-4821',
            uppercase: true,
          ),
          const SizedBox(height: 4),
          const Text(
            'Customers and staff use this code to identify your store. You can edit it.',
            style: TextStyle(color: Colors.white38, fontSize: 11),
          ),
          const SizedBox(height: 20),

          // Location section
          const Text('Store Location on Map', style: TextStyle(color: Color(0xFFCDB4DB), fontSize: 13, fontWeight: FontWeight.w600)),
          const SizedBox(height: 10),

          Row(
            children: [
              Expanded(
                child: _LocationButton(
                  icon: Icons.map_rounded,
                  label: lat != null ? 'Location Set ✓' : 'Pick on Map',
                  color: lat != null ? Colors.green : Colors.deepPurple,
                  onTap: onPickMap,
                ),
              ),
              const SizedBox(width: 10),
              Expanded(
                child: _LocationButton(
                  icon: locating ? null : Icons.my_location_rounded,
                  label: locating ? 'Detecting...' : 'Use My Location',
                  color: Colors.blue,
                  onTap: locating ? () {} : onCurrentLocation,
                  loading: locating,
                ),
              ),
            ],
          ),

          if (lat != null) ...[
            const SizedBox(height: 8),
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
              decoration: BoxDecoration(
                color: Colors.green.withValues(alpha: 0.08),
                borderRadius: BorderRadius.circular(8),
                border: Border.all(color: Colors.green.withValues(alpha: 0.25)),
              ),
              child: Row(
                children: [
                  const Icon(Icons.check_circle_rounded, color: Colors.green, size: 14),
                  const SizedBox(width: 8),
                  Text(
                    'Lat: ${lat!.toStringAsFixed(5)}   Lon: ${lon!.toStringAsFixed(5)}',
                    style: const TextStyle(color: Colors.green, fontSize: 12),
                  ),
                ],
              ),
            ),
          ] else ...[
            const SizedBox(height: 8),
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
              decoration: BoxDecoration(
                color: Colors.orange.withValues(alpha: 0.08),
                borderRadius: BorderRadius.circular(8),
                border: Border.all(color: Colors.orange.withValues(alpha: 0.25)),
              ),
              child: const Row(
                children: [
                  Icon(Icons.warning_amber_rounded, color: Colors.orange, size: 14),
                  SizedBox(width: 8),
                  Expanded(
                    child: Text(
                      'Please pick your store location on the map so customers can find you.',
                      style: TextStyle(color: Colors.orange, fontSize: 11),
                    ),
                  ),
                ],
              ),
            ),
          ],

          const SizedBox(height: 28),
          SizedBox(
            width: double.infinity,
            child: ElevatedButton(
              onPressed: isSaving ? null : onNext,
              style: ElevatedButton.styleFrom(
                backgroundColor: AppTheme.primary,
                foregroundColor: Colors.white,
                padding: const EdgeInsets.symmetric(vertical: 16),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
              ),
              child: isSaving
                  ? const SizedBox(width: 20, height: 20, child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white))
                  : const Text('Create Store & Continue', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15)),
            ),
          ),
        ],
      ),
    );
  }

  Widget _field(TextEditingController ctrl, String label, {IconData? icon, String? hint, bool uppercase = false, int maxLines = 1}) {
    return TextField(
      controller: ctrl,
      maxLines: maxLines,
      style: const TextStyle(color: Colors.white, fontSize: 14),
      textCapitalization: uppercase ? TextCapitalization.characters : TextCapitalization.sentences,
      decoration: InputDecoration(
        labelText: label,
        hintText: hint,
        hintStyle: const TextStyle(color: Color(0xFF6B5B8E), fontSize: 12),
        labelStyle: const TextStyle(color: Color(0xFFCDB4DB), fontSize: 12),
        prefixIcon: icon != null ? Icon(icon, color: const Color(0xFFCDB4DB), size: 16) : null,
        filled: true,
        fillColor: const Color(0x1AFFFFFF),
        contentPadding: const EdgeInsets.symmetric(horizontal: 12, vertical: 12),
        border: OutlineInputBorder(borderRadius: BorderRadius.circular(10), borderSide: const BorderSide(color: Color(0x33FFFFFF))),
        enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(10), borderSide: const BorderSide(color: Color(0x33FFFFFF))),
        focusedBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(10), borderSide: BorderSide(color: AppTheme.primary)),
      ),
    );
  }
}

class _LocationButton extends StatelessWidget {
  final IconData? icon;
  final String label;
  final Color color;
  final VoidCallback onTap;
  final bool loading;

  const _LocationButton({required this.icon, required this.label, required this.color, required this.onTap, this.loading = false});

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: onTap,
      child: Container(
        padding: const EdgeInsets.symmetric(vertical: 12, horizontal: 10),
        decoration: BoxDecoration(
          color: color.withValues(alpha: 0.1),
          borderRadius: BorderRadius.circular(10),
          border: Border.all(color: color.withValues(alpha: 0.35)),
        ),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            loading
                ? SizedBox(width: 14, height: 14, child: CircularProgressIndicator(strokeWidth: 2, color: color))
                : Icon(icon, color: color, size: 16),
            const SizedBox(width: 6),
            Flexible(child: Text(label, style: TextStyle(color: color, fontSize: 12, fontWeight: FontWeight.w600), textAlign: TextAlign.center)),
          ],
        ),
      ),
    );
  }
}

// ── Step 2: Inventory Upload ────────────────────────────────────────────────

class _StepInventory extends StatelessWidget {
  final String storeId;
  final String storeName;
  final BulkUpsertProductsUseCase bulkUpsertUseCase;
  final GetUploadLogsUseCase getLogsUseCase;
  final VoidCallback onSkip;
  final VoidCallback onDone;

  const _StepInventory({
    super.key,
    required this.storeId,
    required this.storeName,
    required this.bulkUpsertUseCase,
    required this.getLogsUseCase,
    required this.onSkip,
    required this.onDone,
  });

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.fromLTRB(24, 32, 24, 32),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Container(
            width: 56, height: 56,
            decoration: BoxDecoration(
              color: Colors.orange.withValues(alpha: 0.15),
              borderRadius: BorderRadius.circular(16),
            ),
            child: const Icon(Icons.upload_file_rounded, color: Colors.orange, size: 28),
          ),
          const SizedBox(height: 16),
          const Text('Upload Inventory', style: TextStyle(color: Colors.white, fontSize: 24, fontWeight: FontWeight.bold)),
          const SizedBox(height: 6),
          const Text('Upload your product list via Excel. You can also do this later from the Products section.', style: TextStyle(color: Color(0xFFCDB4DB), fontSize: 14)),
          const SizedBox(height: 8),
          _StepIndicator(current: 1),
          const SizedBox(height: 32),

          // Upload button
          SizedBox(
            width: double.infinity,
            child: ElevatedButton.icon(
              onPressed: () async {
                final uploaded = await Navigator.push<bool>(
                  context,
                  MaterialPageRoute(
                    builder: (_) => BulkUploadPage(
                      storeId: storeId,
                      storeName: storeName,
                      useCase: bulkUpsertUseCase,
                      getLogsUseCase: getLogsUseCase,
                    ),
                  ),
                );
                // Only advance to Done step if upload actually completed
                // Pressing back returns null — stay on inventory step
                if (uploaded == true) onDone();
              },
              icon: const Icon(Icons.upload_rounded),
              label: const Text('Upload Excel File', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15)),
              style: ElevatedButton.styleFrom(
                backgroundColor: Colors.orange,
                foregroundColor: Colors.white,
                padding: const EdgeInsets.symmetric(vertical: 16),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
              ),
            ),
          ),
          const SizedBox(height: 14),
          SizedBox(
            width: double.infinity,
            child: OutlinedButton(
              onPressed: onSkip,
              style: OutlinedButton.styleFrom(
                foregroundColor: Colors.white60,
                side: const BorderSide(color: Colors.white24),
                padding: const EdgeInsets.symmetric(vertical: 14),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
              ),
              child: const Text('Skip for Now — Add Products Manually Later'),
            ),
          ),
        ],
      ),
    );
  }
}

// ── Step 3: Done ─────────────────────────────────────────────────────────────

class _StepDone extends StatelessWidget {
  final String storeName;
  final String storeCode;
  final VoidCallback onGoToDashboard;

  const _StepDone({super.key, required this.storeName, required this.storeCode, required this.onGoToDashboard});

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.fromLTRB(24, 64, 24, 32),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.center,
        children: [
          Container(
            width: 80, height: 80,
            decoration: BoxDecoration(
              color: Colors.green.withValues(alpha: 0.15),
              shape: BoxShape.circle,
            ),
            child: const Icon(Icons.check_circle_rounded, color: Colors.green, size: 48),
          ),
          const SizedBox(height: 24),
          const Text('Your Store is Live!', style: TextStyle(color: Colors.white, fontSize: 26, fontWeight: FontWeight.bold), textAlign: TextAlign.center),
          const SizedBox(height: 10),
          Text(storeName, style: const TextStyle(color: AppTheme.primary, fontSize: 18, fontWeight: FontWeight.w600), textAlign: TextAlign.center),
          const SizedBox(height: 16),
          if (storeCode.isNotEmpty) ...[
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 10),
              decoration: BoxDecoration(
                color: AppTheme.primary.withValues(alpha: 0.12),
                borderRadius: BorderRadius.circular(10),
                border: Border.all(color: AppTheme.primary.withValues(alpha: 0.35)),
              ),
              child: Column(
                children: [
                  const Text('Your Store Code', style: TextStyle(color: Color(0xFFCDB4DB), fontSize: 11)),
                  const SizedBox(height: 4),
                  Text(storeCode, style: const TextStyle(color: Colors.white, fontSize: 22, fontWeight: FontWeight.bold, letterSpacing: 2)),
                ],
              ),
            ),
            const SizedBox(height: 10),
            const Text(
              'Share this code with your staff so they can log in to the DQ Staff app.',
              style: TextStyle(color: Colors.white54, fontSize: 12),
              textAlign: TextAlign.center,
            ),
          ],
          const Spacer(),
          SizedBox(
            width: double.infinity,
            child: ElevatedButton(
              onPressed: onGoToDashboard,
              style: ElevatedButton.styleFrom(
                backgroundColor: AppTheme.primary,
                foregroundColor: Colors.white,
                padding: const EdgeInsets.symmetric(vertical: 16),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(14)),
              ),
              child: const Text('Go to Dashboard', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
            ),
          ),
        ],
      ),
    );
  }
}

// ── Shared: Step Indicator ───────────────────────────────────────────────────

class _StepIndicator extends StatelessWidget {
  final int current;
  const _StepIndicator({required this.current});

  @override
  Widget build(BuildContext context) {
    return Row(
      children: List.generate(3, (i) {
        final active = i == current;
        final done = i < current;
        return Expanded(
          child: Row(
            children: [
              Expanded(
                child: AnimatedContainer(
                  duration: const Duration(milliseconds: 300),
                  height: 4,
                  decoration: BoxDecoration(
                    color: done
                        ? Colors.green
                        : active
                            ? AppTheme.primary
                            : Colors.white12,
                    borderRadius: BorderRadius.circular(2),
                  ),
                ),
              ),
              if (i < 2) const SizedBox(width: 4),
            ],
          ),
        );
      }),
    );
  }
}
