// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9HmJU2-5PuXQ3IlOxqEJ2YB4H6D0kqvQ',
    appId: '1:17681865839:web:71f4906f9fc83989b4019a',
    messagingSenderId: '17681865839',
    projectId: 'dqueue-716ad',
    authDomain: 'dqueue-716ad.firebaseapp.com',
    databaseURL: 'https://dqueue-716ad-default-rtdb.firebaseio.com',
    storageBucket: 'dqueue-716ad.appspot.com',
    measurementId: 'G-NB5NSPRLNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdAEa_YkPJ3oWpK-C2li6ftZ-SlVM_tKc',
    appId: '1:17681865839:android:98b9e51304930692b4019a',
    messagingSenderId: '17681865839',
    projectId: 'dqueue-716ad',
    databaseURL: 'https://dqueue-716ad-default-rtdb.firebaseio.com',
    storageBucket: 'dqueue-716ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpd0-_wzQlwuGeHSyj6iucA1zDaFahYds',
    appId: '1:17681865839:ios:b33bdd9bb0751fdbb4019a',
    messagingSenderId: '17681865839',
    projectId: 'dqueue-716ad',
    databaseURL: 'https://dqueue-716ad-default-rtdb.firebaseio.com',
    storageBucket: 'dqueue-716ad.appspot.com',
    androidClientId: '17681865839-9unt7skg34reuod72rfavri8l1hnv4st.apps.googleusercontent.com',
    iosClientId: '17681865839-bneifuavqsilep14li4fo9sg2us80bsm.apps.googleusercontent.com',
    iosBundleId: 'com.example.dqAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpd0-_wzQlwuGeHSyj6iucA1zDaFahYds',
    appId: '1:17681865839:ios:b33bdd9bb0751fdbb4019a',
    messagingSenderId: '17681865839',
    projectId: 'dqueue-716ad',
    databaseURL: 'https://dqueue-716ad-default-rtdb.firebaseio.com',
    storageBucket: 'dqueue-716ad.appspot.com',
    androidClientId: '17681865839-9unt7skg34reuod72rfavri8l1hnv4st.apps.googleusercontent.com',
    iosClientId: '17681865839-bneifuavqsilep14li4fo9sg2us80bsm.apps.googleusercontent.com',
    iosBundleId: 'com.example.dqAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnCUh272QwWdP_q-X5lYgf_XYC6yZg4EM',
    appId: '1:17681865839:web:9c0e623d507e8fbab4019a',
    messagingSenderId: '17681865839',
    projectId: 'dqueue-716ad',
    authDomain: 'dqueue-716ad.firebaseapp.com',
    databaseURL: 'https://dqueue-716ad-default-rtdb.firebaseio.com',
    storageBucket: 'dqueue-716ad.appspot.com',
    measurementId: 'G-J7C8LPMDCT',
  );
}
